[versions]
androidGradlePlugin = "8.4.2"
kotlinPlugin = "2.0.0"
gradleKtlint = "12.1.1"
activity-ktx = "1.9.2"
androidx-core = "1.6.1"
appcompat = "1.7.0"
browser = "1.8.0"
constraintlayout = "2.1.4"
core = "4.6.2"
core-ktx = "1.13.1"
core-splashscreen = "1.0.1"
datastore-preferences = "1.1.1"
fragment-ktx = "1.6.2"
gson = "2.11.0"
dagger-hilt = "2.51.1"
junit = "4.13.2"
junit-ktx = "1.2.1"
kotlinx-coroutines-android = "1.8.1"
legacy-support-v4 = "1.0.0"
lifecycle = "2.8.3"
material = "1.12.0"
navigation-fragment-ktx = "2.7.7"
okhttp = "4.12.0"
preference-ktx = "1.2.1"
r8 = "8.3.37"
recyclerview = "1.3.2"
retrofit_version = "2.11.0"
moshi_version ="1.15.1"
room = "2.6.1"
runner = "1.6.1"
shimmer = "0.5.0"
swiperefreshlayout = "1.1.0"
ksp = "2.0.0-1.0.23"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy-support-v4" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-fragment-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room = { module = "androidx.room:room", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit-ktx" }
androidx-test-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit-ktx" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-core" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-core" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-core" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "runner" }

dagger-hilt = { module = "com.google.dagger:dagger-hilt", version.ref = "dagger-hilt" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger-hilt" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-android" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit_version" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit_version" }
moshi-kotlin = {module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi_version"}
moshi-kotlin-codegen = {module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi_version"}

okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

markwon-core = { module = "io.noties.markwon:core", version.ref = "core" }
code-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { module = "junit:junit", version.ref = "junit" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
tools-r8 = { module = "com.android.tools:r8", version.ref = "r8" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation-fragment-ktx" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradleKtlint" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
