---
name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
    paths-ignore:
      -'fastlane/**'
      -'README.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Kotlin Linter
        run: ./gradlew app:ktlintCheck --info
      - name: Generate debug build
        run: ./gradlew assembleDebug
      - name: Execute exodus-standalone
        uses: docker://exodusprivacy/exodus-standalone:v1.3.1
        with:
          args: /github/workspace/app/build/outputs/apk/debug/app-debug.apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app_debug
          path: app/build/outputs/apk/debug/app-debug.apk
